Enroll activity branch
Maua-Dev/smile_mss_activity pull request #11
Opened 2023-01-15 04:09 UTC by Briqz23

2023-01-15 14:01 UTC, JoaoVitorBranco requested changes

2023-01-15 14:01 UTC, JoaoVitorBranco commented on tests/modules/enroll_activity/app/test_enroll_activity_presenter.py
> +              assert json.loads(response["body"]) == 'No items found for Activity'
Quando for fazer o presenter, podem somente colocar **_test_<nome da rota>_presenter_<nome do status code http>_**

ex: test_enroll_activity_presenter_bad_request

Provavelmente vcs copiaram esse teste do drop_activity e adaptaram pra vcs. O Soller é psicopata, n precisa criar tantos testes pra presenter não kkkkkk O mínimo q eu gostaria seria um teste pra cada tipo (possível de ser retornado) de status code http. Nesse caso, 2 para Created (201) (já que foram criados enrollments no banco de dados, sendo que IN_QUEUE tem uma json.loads(response["body"])['message'] diferente de ENROLLED), uma pra BadRequest (400), uma pra Forbidden(403) e uma pra NotFound(404)

2023-01-15 20:31 UTC, VgsStudio requested changes

2023-01-15 20:31 UTC, VgsStudio commented on src/shared/infra/repositories/activity_repository_mock.py
> +            Enrollment(activity=self.activities[1], user=self.users[1], state=ENROLLMENT_STATE.IN_QUEUE,
sipa isso vai dar erro nos tests quando mandar pra dev

por que mudaram duas enrollment?

2023-01-15 20:31 UTC, VgsStudio commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +
verificar se o user existe

2023-01-15 20:31 UTC, VgsStudio commented on src/modules/enroll_activity/app/enroll_activity_controller.py
> +from src.modules.enroll_activity.app.enroll_activity_usecase import EnrollActivityUsecase
tirar até depos do app, .enroll_activity_usecase apenas

2023-01-15 20:31 UTC, VgsStudio commented on src/modules/enroll_activity/app/enroll_activity_controller.py
> +from src.modules.enroll_activity.app.enroll_activity_viewmodel import EnrollActivityViewmodel
tirar até depos do app, .enroll_activity_viewmodel apenas

2023-01-15 20:31 UTC, VgsStudio commented on src/modules/enroll_activity/app/enroll_activity_presenter.py
> +from src.modules.enroll_activity.app.enroll_activity_controller import EnrollActivityController
tirar até depos do app, .enroll_activity_controller apenas

2023-01-15 20:31 UTC, VgsStudio commented on src/modules/enroll_activity/app/enroll_activity_presenter.py
> +from src.modules.enroll_activity.app.enroll_activity_usecase import EnrollActivityUsecase
tirar até depos do app, .enroll_activity_usecase apenas

(o presenter e o controller TEM que fazer isso, não pode ter um src.modules)

2023-01-16 23:21 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +        if type(enrollment) != None:
não seria is not None?

2023-01-16 23:26 UTC, Briqz23 commented on src/shared/infra/repositories/activity_repository_mock.py
> +            Enrollment(activity=self.activities[1], user=self.users[1], state=ENROLLMENT_STATE.IN_QUEUE,
ok!

2023-01-16 23:57 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        user = self.repo.get_user(user_id),
ok

2023-01-16 23:58 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        user = self.repo.get_user(user_id),
fizemos a validação de de NoItemsFound pro User

2023-01-17 00:31 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        user = self.repo.get_user(user_id),
ok

2023-01-17 00:39 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +            if activity.accepting_new_enrollments == True:
ok

2023-01-17 00:40 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                if  activity.taken_slots < activity.total_slots:
ok

2023-01-17 00:44 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                    return enrollment
ok

2023-01-17 00:45 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        activity = self.repo.get_activity(code),
ok

2023-01-17 00:45 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        activity = self.repo.get_activity(code),
ok

2023-01-17 00:46 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +                        user = self.repo.get_user(user_id),
ok

2023-01-17 00:46 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    #test user_id
ok

2023-01-17 00:50 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +
ok

2023-01-17 00:53 UTC, Briqz23 commented on src/shared/infra/repositories/activity_repository_mock.py
ok

2023-01-17 01:08 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +        assert enrollment_activity.activity.taken_slots >= enrollment_activity.activity.total_slots
ok

2023-01-17 01:08 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +        assert enrollment_activity.activity.taken_slots < enrollment_activity.activity.total_slots
okey

2023-01-17 01:17 UTC, Briqz23 commented on src/shared/infra/repositories/activity_repository_mock.py
> +            Enrollment(activity=self.activities[1], user=self.users[1], state=ENROLLMENT_STATE.IN_QUEUE,
ok

2023-01-17 01:18 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_presenter.py
> +              assert json.loads(response["body"]) == "Field code is missing"
ok

2023-01-17 01:58 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_viewmodel.py
> +              assert enrollActivityViewmodel == {'activity': {'code': 'ECM2345', 'title': 'Atividade da ECM 2345', 'description': 'Isso é uma atividade', 'activity_type': 'COURSE', 'is_extensive': Fa
ok

2023-01-17 02:04 UTC, JoaoVitorBranco commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +        if type(enrollment) != None:
yes my honey

2023-01-17 21:06 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_is_not_none(self):
ok

2023-01-17 21:14 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_accepting_new_enrollments(self):
ok

2023-01-17 21:16 UTC, Briqz23 commented on src/modules/enroll_activity/app/enroll_activity_viewmodel.py
> +            "message": "the enrollment has been done"
ok

2023-01-17 21:18 UTC, Briqz23 commented on tests/shared/infra/repositories/test_activity_repository_mock.py
> +        assert user is not None
ok

2023-01-17 21:21 UTC, Briqz23 commented on tests/shared/infra/repositories/test_activity_repository_mock.py
> +        repo.create_enrollment(enrollment=enrollment)
ok

2023-01-17 21:23 UTC, Briqz23 commented on tests/shared/infra/repositories/test_activity_repository_mock.py
> +        assert repo.enrollments[0].activity == repo.get_activity('ECM2345')
substituí pela linha 50

2023-01-17 21:56 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
> +    def test_enroll_activity_controller_forbidden_action(self):
ok

2023-01-17 22:15 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
> +
em _test_enroll_activity_controller_forbidden_action_ tem um request referente à _repo.enrollments[2].activity.code_, onde tem essa condição de _accepting_new_enrollments == True_, não?

2023-01-17 23:17 UTC, LucasRomanato0 commented on src/shared/infra/repositories/activity_repository_mock.py
> +
ok

2023-01-17 23:17 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_enrolled(self):
ok

2023-01-17 23:19 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_in_queue(self):
ok

2023-01-17 23:30 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_viewmodel.py
> +            "message": "the enrollment has been done"
ok

2023-01-17 23:59 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
> +    def test_enroll_activity_controller(self):
ok

2023-01-18 00:02 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
> +
ok

2023-01-18 00:05 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +        assert enrollment_activity.activity.taken_slots < enrollment_activity.activity.total_slots
ok

2023-01-18 00:09 UTC, LucasRomanato0 commented on tests/modules/enroll_activity/app/test_enroll_activity_presenter.py
> +       def test_enroll_activity_presenter(self):
ok

2023-01-18 00:12 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_usecase.py
> +
ok

2023-01-18 00:14 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_controller.py
> +from src.modules.enroll_activity.app.enroll_activity_usecase import EnrollActivityUsecase
ok

2023-01-18 00:15 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_controller.py
> +from src.modules.enroll_activity.app.enroll_activity_viewmodel import EnrollActivityViewmodel
ok

2023-01-18 00:16 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_presenter.py
> +from src.modules.enroll_activity.app.enroll_activity_controller import EnrollActivityController
ok

2023-01-18 00:16 UTC, LucasRomanato0 commented on src/modules/enroll_activity/app/enroll_activity_presenter.py
> +from src.modules.enroll_activity.app.enroll_activity_usecase import EnrollActivityUsecase
ok

2023-01-18 00:27 UTC, JoaoVitorBranco commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
Seria melhor se o teste da "activity not found" se relacionasse ao atributo "code", mas vo deixa essa passa.
test_enroll_activity_controller_activity_code_not_found

2023-01-18 00:32 UTC, JoaoVitorBranco commented on src/shared/domain/repositories/activity_repository_interface.py
> +
@abstractmethod antes de todos os métodos

2023-01-18 00:32 UTC, JoaoVitorBranco commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_accepting_new_enrollments(self):
qual a importância desse teste? (me mandem o motivo por aq ou pelo zap)

2023-01-18 00:32 UTC, JoaoVitorBranco commented on src/modules/enroll_activity/app/enroll_activity_viewmodel.py
> +            "message": "the enrollment has been done"
não tinha visto o comentário, my bad

2023-01-18 00:36 UTC, JoaoVitorBranco commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
test_enroll_activity_controller_forbidden_action... vou deixar passar, mas a ideia dos comentários sobre mudar o nome das funções é que um cara que futuramente veja esse código entenda o motivo do teste, ou seja, deixar o código mais verboso

2023-01-18 00:37 UTC, JoaoVitorBranco commented on tests/modules/enroll_activity/app/test_enroll_activity_controller.py
> +        assert response.body['message'] == "the enrollment was enrolled"
test_enroll_activity_controller_enrolled (melhorar verbosidade)

2023-01-18 01:22 UTC, Briqz23 commented on src/shared/domain/repositories/activity_repository_interface.py
> +
ok

2023-01-18 01:27 UTC, Briqz23 commented on tests/modules/enroll_activity/app/test_enroll_activity_usecase.py
> +    def test_enroll_activity_usecase_accepting_new_enrollments(self):
A intenção era ser um primeiro teste para verificar as coisas mais simples, nesse caso ver se as informações estavam sendo capturadas de forma correta

2023-01-18 02:00 UTC, JoaoVitorBranco approved these changes

2023-01-18 02:02 UTC, VgsStudio approved these changes
LGTM

2023-01-18 02:03 UTC, merged