Feature delete activity
Maua-Dev/smile_mss_activity pull request #15
Opened 2023-01-18 22:02 UTC by VgsStudio

Deleta uma atividade e usar o método batch_update_enrollment para atualizar todas as suas inscrições

2023-01-19 01:27 UTC, JoaoVitorBranco requested changes

2023-01-19 01:27 UTC, JoaoVitorBranco commented on tests/modules/delete_activity/app/test_delete_activity_usecase.py
> +
deleta uma atividade que não tem inscrição tbm

2023-01-19 01:27 UTC, JoaoVitorBranco commented on src/modules/delete_activity/app/delete_activity_controller.py
> +        except WrongTypeParameter as err:
pode tira

2023-01-19 01:27 UTC, JoaoVitorBranco commented on tests/modules/delete_activity/app/test_delete_activity_presenter.py
> +
verifica msg dos erros

2023-01-19 16:55 UTC, VgsStudio commented on tests/modules/delete_activity/app/test_delete_activity_presenter.py
> +
teoricamente já faço isso no controller, mas feito!

2023-01-19 17:01 UTC, VgsStudio commented on tests/modules/delete_activity/app/test_delete_activity_usecase.py
> +
ok

2023-01-19 17:01 UTC, VgsStudio commented on src/modules/delete_activity/app/delete_activity_controller.py
> +        except WrongTypeParameter as err:
ok

2023-01-20 13:23 UTC, JoaoVitorBranco approved these changes

2023-01-20 13:23 UTC, merged