Update activity
Maua-Dev/smile_mss_activity pull request #25
Opened 2023-01-24 01:23 UTC by VgsStudio

2023-01-25 01:57 UTC, JoaoVitorBranco requested changes

2023-01-25 01:57 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_usecase.py
> +        new_activity = Activity(
pra q serve essa variável?

2023-01-25 01:57 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_usecase.py
> +                 new_start_date: int, new_duration: int, new_link: str, new_place: str,
:= None

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +        assert repo.activities[0].description == update_activity.description
faz uma verificação hard-codada que essa descrição/título/qqr parâmetro é novo, pelo menos 1

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +
faz teste mudando, apenas, 1 parâmetro

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +    def test_update_activity_invalid_enum(self):
mudar nome do teste (deixar + verboso)

2023-01-25 01:57 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_usecase.py
> +                 new_start_date: int, new_duration: int, new_link: str, new_place: str,
para link

2023-01-25 01:57 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_controller.py
> +                    raise WrongTypeParameter('new_stop_accepting_new_enrollments_before', 'int',
tira

2023-01-25 01:57 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_controller.py
> +                raise WrongTypeParameter('new_start_date', 'int', type(new_start_date).__class__.__name__)
tira

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_controller.py
> +
Testa invalid_responsible_professors e not_found desse parâmetro tbm

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_controller.py
> +
test new_speakers not a list

2023-01-25 01:57 UTC, JoaoVitorBranco commented on tests/modules/update_activity/app/test_update_activity_presenter.py
> +    def test_update_activity_presenter_missing_parameter_codey(self):
nome do teste

2023-01-25 02:15 UTC, VgsStudio commented on src/modules/update_activity/app/update_activity_usecase.py
> +        new_activity = Activity(
testar coisas da atividade

2023-01-25 22:59 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +        assert repo.activities[0].description == update_activity.description
sinceramente não entendo a razão, mas feito!

2023-01-25 23:05 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +
ok

2023-01-25 23:06 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_usecase.py
> +    def test_update_activity_invalid_enum(self):
ok

2023-01-25 23:07 UTC, VgsStudio commented on src/modules/update_activity/app/update_activity_controller.py
> +                    raise WrongTypeParameter('new_stop_accepting_new_enrollments_before', 'int',
ok

2023-01-25 23:07 UTC, VgsStudio commented on src/modules/update_activity/app/update_activity_controller.py
> +                raise WrongTypeParameter('new_start_date', 'int', type(new_start_date).__class__.__name__)
ok

2023-01-25 23:11 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_controller.py
> +
ok ok

2023-01-25 23:15 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_controller.py
> +
ok

2023-01-25 23:16 UTC, VgsStudio commented on tests/modules/update_activity/app/test_update_activity_presenter.py
> +    def test_update_activity_presenter_missing_parameter_codey(self):
FEITO

2023-01-26 01:59 UTC, JoaoVitorBranco requested changes

2023-01-26 01:59 UTC, JoaoVitorBranco commented on src/modules/update_activity/app/update_activity_usecase.py
> +                 new_start_date: int, new_duration: int, new_link: str, new_place: str,
verbosidade do código, mostrar oq é opcional

2023-01-27 00:59 UTC, VgsStudio commented
pelo AMOR DE DEUS APROVA ESSE PR

2023-01-27 01:08 UTC, JoaoVitorBranco approved these changes

2023-01-27 01:08 UTC, merged